services:
  modsecurity:
    build: ./requirements/modsecurity
    container_name: modsecurity
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./requirements/modsecurity/log:/var/log/modsecurity:rw
    depends_on:
      - backend
    networks:
      - internal_network 
    restart: always

  backend:
    build: ./requirements/backend
    container_name: backend
    expose:
      - "80"
    networks:
      - internal_network 
    restart: always

networks:
  internal_network:
    driver: bridge